fq1:
    class: File
    path: ./reads1.fastq.gz
    format: http://edamontology.org/format_3989
fq2:
    class: File
    path: ./reads2.fastq.gz
    format: http://edamontology.org/format_3989

ref: 
    class: File
	path: ./ref.fa
	format: http://edamontology.org/format_1929
